apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: istio-ingress
  namespace: kube-system
spec:
  repo: https://devopsapp84.github.io/helm-repository
  chart: istio-ingress
  targetNamespace: istio-ingress
  #valuesContent: |-
  #  global:
  #    hub: docker.io/istio
  #    tag: 1.13.3