apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: istio-base
  namespace: kube-system
spec:
  repo: https://devopsapp84.github.io/helm-repository
  chart: base
  targetNamespace: istio-system
  #valuesContent: |-
    