---
kind: Simple
apiVersion: k3d.io/v1alpha4
metadata:
  name: dev-cluster-121
servers: 1
agents: 1
image: docker.io/rancher/k3s:v1.21.11-k3s1
subnet: "172.20.0.0/16"
ports:
# For vCluster
- port: 4450:443
  nodeFilters:
  - loadbalancer
# For ArgoCD
- port: 18090:8080
  nodeFilters:
  - loadbalancer
- port: 18443:8443
  nodeFilters:
  - loadbalancer
# For sample application
- port: 19090:9090
  nodeFilters:
  - loadbalancer
- port: 19091:9091
  nodeFilters:
  - loadbalancer
- port: 19092:9092
  nodeFilters:
  - loadbalancer
- port: 19093:9093
  nodeFilters:
  - loadbalancer
options:
  k3d:
    wait: true
    timeout: 1m0s
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false
    loadbalancer:
      configOverrides:
      - settings.workerConnections=2048
  k3s:
    extraArgs:
    - arg: --no-deploy=traefik
      nodeFilters:
      - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
